version: '3.9'
services:
  app:
    container_name: docker-node-mongo
    hostname: webapp
    restart: always
    build:
      context: .
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
      - nginx
  mongo:
    container_name: mongo
    build:
      context: utils/mongoDB
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    build:
      context: utils/redis
    ports:
      - '6379:6379'
  nginx:
    container_name: nginx
    build:
      context: utils/nginx
    hostname: nginx
    ports:
      - '80:80'
