version: '3.9'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'
