version: '3.9'
services:
  app:
    container_name: express
    hostname: webapp
    restart: always
    image: kartowkaa/webapp
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
      - nginx
    networks:
      - webapp-network
  mongo:
    container_name: mongo
    build:
      context: utils/mongoDB
    ports:
      - '27017:27017'
    networks:
      - webapp-network
  redis:
    container_name: redis
    build:
      context: utils/redis
    ports:
      - '6379:6379'
    networks:
      - webapp-network
  nginx:
    container_name: nginx
    build:
      context: utils/nginx
    hostname: nginx
    ports:
      - '80:80'
    networks:
      - webapp-network
networks:
  webapp-network:
    external: true
