###
GET http://localhost:3000/
###
GET http://localhost:3000/post
###
GET http://localhost:3000/post/623328df259021aed6a4aafb
###
GET http://localhost:3000/post?sender=Fleysher
###
POST http://localhost:3000/post
Content-Type: application/json

{
    "message":"this is my new message1",
    "sender":"Fleysher"
}