name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_ACCESSTOKEN: ${{secrets.DOCKER_ACCESSTOKEN}}
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
      uses: docker/login-action@v1.14.1
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Username used to log against the Docker registry
        username: DOCKER_USER
        # Password or personal access token used to log against the Docker registry
        password: DOCKER_ACCESSTOKEN
        # Specifies whether the given registry is ECR (auto, true or false)
        # ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        logout: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile kartowkaa/webapp:$(date +%s)
    - name: docker push
      run: |
        docker push kartowkaa/webapp:$(date +%s)
